---
- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: cleanup tempdir
  file:
    state: absent
    path: "{{ tempdir_path }}"
  become: no
  delegate_to: localhost
  delegate_facts: true
  run_once: true
