---
- hosts: ubuntu
  become: yes

  vars_files: 
   - vars/config.yml

  #vars:
  #  vault: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv-v2/data/secret/ansible auth_method=approle') }}"

  tasks:
    - name: ping node1
        shell: ping -c 1 -w 2 10.10.30.11
        ignore_errors: true

    - name: ping node2
        shell: ping -c 1 -w 2 10.10.30.12
        ignore_errors: true
