---
- hosts: ubuntu
  gather_facts: no

  pre_tasks:
    - name: ping node1
      shell: ping -c 1 -w 2 10.10.30.11
      ignore_errors: true

    - name: ping node2
      shell: ping -c 1 -w 2 10.10.30.12
      ignore_errors: true
