---
- hosts: ubuntu
  gather_facts: no
  connection: local

  pre_tasks:
    - name: check node1 port 22 connection
      shell: nc 10.10.30.11 -zv 22
      ignore_errors: true

    - name: check node2 port 22 connection
      shell: nc 10.10.30.12 -zv 22
      ignore_errors: true
