---
- hosts: rpi
  become: yes
  vars_files:
    - vars/config.yml
  #vars:
  #  vault: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv-v2/data/secret/ansible auth_method=approle') }}"
  roles:
    - role: jnv.unattended-upgrades
      unattended_origins_patterns:
      - 'origin=Raspbian,codename=${distro_codename},label=Raspbian'
      unattended_mail: "{{ vault.secret_unattended_mail }}" 
      unattended_mail_only_on_error: true
      unattended_automatic_reboot: true
      unattended_automatic_reboot_time: '03:00'
      unattended_update_days: {"Fri"}
    - role: oefenweb.postfix
      vars:
        postfix_aliases:
          - user: rpi
            alias: "{{ vault.secret_alias }}"
        postfix_relayhost: "{{ vault.secret_postfix_relayhost }}"
        postfix_relaytls: true
        postfix_smtp_tls_cafile: /etc/ssl/certs/ca-certificates.crt
        postfix_sasl_user: "{{ vault.secret_postfix_sasl_user }}"
        postfix_sasl_password: "{{ vault.secret_postfix_sasl_password }}"
