---
- hosts: rpi
  become: yes

  ## Secrets from ansible-vault
  # vars_files:
  #  - vars/config.yml

  ## Secrets from hashi-vault
  vars:
    vault: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv-v2/data/secret/ansible auth_method=approle') }}"

  roles:
    - role: jnv.unattended-upgrades
      unattended_origins_patterns:
      - 'origin=Raspbian,codename=${distro_codename},label=Raspbian'
      unattended_mail: "{{ vault._unattended_mail }}" 
      unattended_mail_only_on_error: true
      unattended_automatic_reboot: true
      unattended_automatic_reboot_time: '03:00'
      unattended_update_days: {"Fri"}

    - role: oefenweb.postfix
      vars:
        postfix_aliases:
          - user: rpi
            alias: "{{ vault._alias }}"
        postfix_relayhost: "{{ vault._postfix_relayhost }}"
        postfix_relaytls: true
        postfix_smtp_tls_cafile: /etc/ssl/certs/ca-certificates.crt
        postfix_sasl_user: "{{ vault._postfix_sasl_user }}"
        postfix_sasl_password: "{{ vault._postfix_sasl_password }}"

    - { role: pihole-ufw, when: inventory_hostname == 'pihole' }

  # tasks:
  #   - name: Apply UFW rules to pihole
  #     include_tasks: roles/common/tasks/pihole_ufw.yml
  #     when: inventory_hostname == 'pihole'

