---
roles:
  - name: oefenweb.postfix
  - name: hifis.unattended_upgrades
  - name: geerlingguy.security
  - src: andrewrothstein.docker_engine

collections:
  - name: community.hashi_vault
  - name: community.general
