---
roles:
  - name: oefenweb.postfix
  - name: hifis.unattended_upgrades
  - name: geerlingguy.security
  - name: andrewrothstein.docker_engine
  - name: maxhoesel.ddclient

collections:
  - name: community.hashi_vault
  - name: community.general
