---
- name: Mkdir -p {{ docker_engine_tls_dir }}
  become: true
  become_user: root
  ansible.builtin.file:
    path: '{{ docker_engine_tls_dir }}'
    state: directory
    mode: '755'
- name: Install keys/certs
  ansible.builtin.include_role:
    name: andrewrothstein.tls
  vars:
    tls_become: true
    tls_become_user: root
    tls_src: '{{ docker_engine_tls.pki_dir }}'
    tls_dest: '{{ docker_engine_tls_dir }}'
    tls_dest_chmod:
      owner: root
      grp: root
