all:
  hosts:
    node1:
      ansible_host: 10.10.30.11
    node2:
      ansible_host: 10.10.30.12
    pihole:
      ansible_host: 10.10.10.10
    datamax:
      ansible_host: 10.10.20.20
  children:
    k8s:
      hosts:
        node1:
        node2:
    ubuntu:
      hosts:
        node1:
        node2:
    rpi:
      hosts:
        datamax:
        pihole:
    multi:
      children:
        k8s:
        rpi:
