all:
  hosts:
    node1:
    node2:
  children:
    k8s:
      hosts:
        node1:
        node2:
    ubuntu:
      hosts:
        node1:
        node2:
    rpi:
      hosts:
        datamax:
        pihole:
    multi:
      children:
        k8s:
        rpi:
