---
- name: Converge
  hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600

- import_playbook: ../../k8s.yml