---
- hosts: all
  become: yes
  gather_facts: no

  # ansible-vault
  # vars_files: 
  #  - vars/config.yml

  # hashi-vault
  vars:
    vault: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv-v2/data/secret/ansible auth_method=approle') }}"

  tasks:
    - block:
        - import_role:
            name: ssh-ca-client
          vars:
            VAULT_ADDR: "{{ lookup('env','VAULT_ADDR') }}"
            VAULT_ROLE_ID: "{{ lookup('env','ANSIBLE_HASHI_VAULT_ROLE_ID') }}"
            VAULT_SECRET_ID: "{{ lookup('env','ANSIBLE_HASHI_VAULT_SECRET_ID') }}"

        - name: Gather facts
          setup:

        - include_role:
            name: nfs-common

        - include_role:
            name: ssh-ca-host
          vars:
            VAULT_ADDR: "{{ lookup('env','VAULT_ADDR') }}"

        - include_role:
            name: oefenweb.postfix
          vars:
            postfix_aliases:
              - user: node_server
                alias: "{{ vault._alias }}"
            postfix_relayhost: "{{ vault._postfix_relayhost }}"
            postfix_relaytls: true
            postfix_smtp_tls_cafile: /etc/ssl/certs/ca-certificates.crt
            postfix_sasl_user: "{{ vault._postfix_sasl_user }}"
            postfix_sasl_password: "{{ vault._postfix_sasl_password }}"

        - include_role:
            name: jnv.unattended-upgrades
          vars:
            unattended_origins_patterns:
            - 'origin=Ubuntu,archive=${distro_codename}-security'
            - 'o=Ubuntu,a=${distro_codename}-updates'
            unattended_update_days: '{"Fri"}'
            unattended_mail: "{{ vault._unattended_mail }}"
            unattended_mail_only_on_error: true
            unattended_automatic_reboot: true
            unattended_automatic_reboot_time: '04:00'

      rescue:
        - include_tasks: roles/ssh-ca-client/tasks/cleanup.yml

      always:
        - include_tasks: roles/ssh-ca-client/tasks/cleanup.yml
