name: Run Ansible Playbook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ansible:
    name: 'Ansible'
    runs-on: self-hosted

    defaults:
      run:
        shell: bash

    steps:
    - name: Import Secrets
      uses: hashicorp/vault-action@v2.3.1
      with:
        url: ${{ secrets.VAULT_ADDR }}
        method: approle
        roleId: ${{ secrets.VAULT_ROLE_ID }}
        secretId: ${{ secrets.VAULT_SECRET_ID }}
        secrets: |
            kv-v2/data/secret/ansible secret_private_key | PRIVATE_KEY ;

    - name: echo test1
      run: echo ${{ secrets.SSH_PRIVATE_KEY }} > ~/test1 && chmod 600 ~/test1 && ls -l ~/test1 && cat ~/test

    - name: ssh test1
      run: ssh -o StrictHostKeyChecking=no -T -i ~/test1 master@10.10.20.20 whoami

    - name: echo test
      run: echo $PRIVATE_KEY > ~/test && chmod 600 ~/test && ls -l ~/test

    - name: test ssh
      run: ssh -o StrictHostKeyChecking=no -T -i ~/test master@10.10.20.20 whoami

    # - name: Checkout
    #   uses: actions/checkout@v2

    # - name: Install dependencies
    #   run: pip install -r requirements.txt

    # - name: Run Ansible Playbook
    #   uses: arillso/action.playbook@master
    #   with:
    #     playbook: all-playbooks.yml
    #     inventory: inventory/hosts.yml
    #     galaxy_file: requirements.yml
    #     #vault_password: ${{secrets.VAULT_PASSWORD}}
    #     #private_key: ${{secrets.SSH_PRIVATE_KEY}}
    #     private_key: $PRIVATE_KEY
    #     verbose: 3
    #   env:
    #     ANSIBLE_HOST_KEY_CHECKING: 'false'
    #     ANSIBLE_DEPRECATION_WARNINGS: 'false'
    #     ANSIBLE_HASHI_VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
    #     ANSIBLE_HASHI_VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
        
