name: Run Ansible Playbook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ansible:
    name: 'Ansible'
    runs-on: self-hosted
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    defaults:
      run:
        shell: bash

    steps:
    - name: Import Secrets
      uses: hashicorp/vault-action@v2.3.1
      with:
        url: ${{ secrets.VAULT_ADDR }}
        method: approle
        roleId: ${{ secrets.VAULT_ROLE_ID }}
        secretId: ${{ secrets.VAULT_SECRET_ID }}
        secrets: |
            kv-v2/data/secret/ansible secret_private_key | SSH_PRIVATE_KEY ;

    - name: Checkout
      uses: actions/checkout@v2

    - name: Add SSH key to ssh-agent
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None ssh-add - >/dev/null

    # Already installed in custom container    
    # - name: Install pip dependencies
    #   run: pip install -r requirements.txt

    - name: Install Ansible collections and roles
      run: ansible-galaxy install -r requirements.yml
    
    - name: Run Ansible Playbook
      run: ansible-playbook -i inventory/hosts.yml all-playbooks.yml
      env:
        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        ANSIBLE_HASHI_VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
        ANSIBLE_HASHI_VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
        ANSIBLE_DEPRECATION_WARNINGS: "False"
        PY_COLORS: "1"
        ANSIBLE_FORCE_COLOR: "1"
