---
name: Run Ansible Playbook

on:
  push:
    branches: [ main ]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  ansible:
    name: 'Ansible'
    runs-on: self-hosted
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Already installed in custom container
    # - name: Install pip dependencies
    #   run: pip install -r requirements.txt

    - name: Install Ansible collections and roles
      run: ansible-galaxy install -r requirements.yml

    - name: Run Ansible Playbook
      run: ansible-playbook -i inventory/hosts.yml all-playbooks.yml
      env:
        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        ANSIBLE_HASHI_VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
        ANSIBLE_HASHI_VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
        ANSIBLE_DEPRECATION_WARNINGS: "False"
        PY_COLORS: "1"
        ANSIBLE_FORCE_COLOR: "1"
