---
name: CI

on:
  pull_request:

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  molecule:
    name: Molecule
    runs-on: self-hosted
    strategy:
      matrix:
        distro:
          - ubuntu2004

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install test dependencies.
        run: pip3 install molecule[docker] yamllint ansible-lint

      - name: Install Ansible collections and roles
        run: ansible-galaxy install -r requirements.yml

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          ANSIBLE_HASHI_VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
          ANSIBLE_HASHI_VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
          ANSIBLE_DEPRECATION_WARNINGS: "False"
    