---
dependencies: []

galaxy_info:
  role_name: security
  author: geerlingguy
  description: Security software installation and configuration.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.10
  platforms:
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - system
    - security
    - fail2ban
    - automatic
    - updates
    - yum
    - apt
    - dnf
    - hardening
